version: 0.2

env:
  git-credential-helper: yes
  parameter-store:
    DOCKER_HUB_USER: '/devops/shared/DOCKER_HUB_USER'
    DOCKER_HUB_PASSWORD: '/devops/shared/DOCKER_HUB_PASSWORD'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
      - npm update -g npm
      - aws --version
      - node -v
  pre_build:
    commands:
      - export APP_BUILD_VERSION=${CODEBUILD_RESOLVED_SOURCE_VERSION}__$(date -u '+%Y-%m-%dT%T+00:00')
      - echo $APP_BUILD_VERSION > ./src/.version
      - cat ./src/.version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_REPOSITORY_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USER --password-stdin
      - docker build -t $DOCKER_REPOSITORY_URI:latest .
      - docker tag $DOCKER_REPOSITORY_URI:latest $DOCKER_REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $DOCKER_REPOSITORY_URI:latest
      - docker push $DOCKER_REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $DOCKER_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json