version: 0.2

env:
  shell: bash
  git-credential-helper: yes
  variables:
    AWS_ENV_PATH: '/gameshq/frontend'
    AWS_REGION: 'us-east-1'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
      - npm update -g npm
      - npm install -g yarn
      - aws --version
      - node -v
      - yarn -v
      - wget https://github.com/Droplr/aws-env/raw/master/bin/aws-env-linux-amd64 -O aws-env
      - chmod +x aws-env

  build:
    commands:
      - eval $(./aws-env --recursive)
      - npm i --legacy-peer-deps
      - NODE_ENV=production npm run build

  post_build:
    commands:
      - aws s3 sync build/. s3://$FRONTEND_BUCKET
