version: 0.2

env:
  shell: bash
  git-credential-helper: yes
  variables:
    AWS_ENV_PATH: '/gameshq/frontend'
    AWS_REGION: 'us-east-1'

phases:
  install:
    commands:
      - n 18
      - npm update -g npm
      - aws --version
      - node -v
      - wget https://github.com/Droplr/aws-env/raw/master/bin/aws-env-linux-amd64 -O aws-env
      - chmod +x aws-env
      - ls -la

  build:
    commands:
      - npm i --legacy-peer-deps
      - eval $(./aws-env --recursive) && npm run build

  post_build:
    commands:
      - aws s3 sync build/. s3://$FRONTEND_BUCKET
