export enum ARENA_ZONE_RING {
    ONE_A = "1A",
    ONE_B = "1B",
    ONE_C = "1C",
    ONE_D = "1D",
    TWO_A = "2A",
    TWO_B = "2B",
    TWO_C = "2C",
    TWO_D = "2D",
    THREE_A = "3A",
    THREE_B = "3B",
    THREE_C = "3C",
    THREE_D = "3D",
    FOUR_A = "4A",
    FOUR_B = "4B",
    FOUR_C = "4C",
    FOUR_D = "4D",
    FIVE = "5",
}
